import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

/**
 * 构建时脚本：扫描 icons 文件夹，生成图标映射文件
 * 运行方式: tsx scripts/generate-icons.ts
 */

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const ICONS_DIR = path.join(__dirname, '../icons')
const ICONS_MAP_FILE = path.join(__dirname, '../src/icons-map.ts')
const ICONS_EXPORTS_FILE = path.join(__dirname, '../src/icons-exports.ts')

// 读取所有 SVG 文件
const iconFiles = fs.readdirSync(ICONS_DIR).filter(file => file.endsWith('.svg'))

// 将文件名转换为图标名（kebab-case -> PascalCase）
function fileNameToIconName(fileName: string): string {
  return fileName
    .replace(/\.svg$/, '')
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

// 读取 SVG 内容并生成映射
const iconsMap: Record<string, string> = {}

for (const file of iconFiles) {
  const filePath = path.join(ICONS_DIR, file)
  const svgContent = fs.readFileSync(filePath, 'utf-8')
  const iconName = fileNameToIconName(file)
  iconsMap[iconName] = svgContent
}

// 生成 TypeScript 文件
const fileNames = iconFiles.map(f => f.replace(/\.svg$/, '')).sort()
const iconNames = Object.keys(iconsMap).sort()

// 生成 icons-map.ts
const iconsMapOutput = `// 此文件由 scripts/generate-icons.ts 自动生成，请勿手动编辑
// Auto-generated by scripts/generate-icons.ts, do not edit manually

/**
 * 图标 SVG 内容映射表
 * 键为图标名（PascalCase），值为 SVG 字符串
 */
export const iconsMap: Record<string, string> = ${JSON.stringify(iconsMap, null, 2)}

/**
 * 所有可用的图标名称列表（PascalCase）
 */
export const iconNames: string[] = ${JSON.stringify(iconNames, null, 2)}

/**
 * 所有可用的图标文件名列表（kebab-case）
 */
export const iconFileNames: string[] = ${JSON.stringify(fileNames, null, 2)}
`

fs.writeFileSync(ICONS_MAP_FILE, iconsMapOutput, 'utf-8')

// 生成所有图标的导出文件
const exportsOutput = `// 此文件由 scripts/generate-icons.ts 自动生成，请勿手动编辑
// Auto-generated by scripts/generate-icons.ts, do not edit manually

import { createIconFromLocal } from './iconFactory'

${iconNames.map(name => `export const ${name} = createIconFromLocal('${name}')`).join('\n')}
`

fs.writeFileSync(ICONS_EXPORTS_FILE, exportsOutput, 'utf-8')

console.log(`✅ 已生成 ${iconNames.length} 个图标的映射文件: ${ICONS_MAP_FILE}`)
console.log(`✅ 已生成 ${iconNames.length} 个图标的导出文件: ${ICONS_EXPORTS_FILE}`)
console.log(`📦 图标列表: ${iconNames.slice(0, 10).join(', ')}...`)

